import { Metadata } from "next";
import Link from "next/link";
import TechLink from "./components/TechLink";
import LinkArrowBtn from "./components/Buttons/LinkArrowBtn";
import AppFeatureItem from "./components/AppFeatureItem";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <section className="pt-5 3xl:pt-12 !bg-transparent ">
      <div className=" mx-auto max-w-screen-xl text-center flex flex-col items-center z-10 relative">
        <Link
          href="https://github.com/nick-r-o-s-e?tab=repositories"
          target="_blank"
          className="duration-200 inline-flex justify-between items-center py-1 px-1 pe-4 mb-7 text-[0.82rem] sm:text-sm text-gray-800 bg-gray-300 rounded-full dark:bg-blue-950 dark:text-blue-300 hover:bg-gray-200 dark:hover:bg-blue-800"
        >
          <span className="text-xs bg-gray-800 dark:bg-blue-600 rounded-full text-white px-4 py-1.5 me-3">
            New
          </span>{" "}
          <span className=" font-medium">
            This is my NextJS and TailwindCSS project! See what&apos;s new
          </span>
          <svg
            className="w-2 h-2 sm:w-2.5 sm:h-2.5 ms-2 rtl:rotate-180"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 6 10"
          >
            <path
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="m1 9 4-4-4-4"
            />
          </svg>
        </Link>

        <h1 className="mb-4 text-5xl xs:text-6xl font-extrabold tracking-tight leading-none text-white drop-shadow-[0_5px_5px_rgba(0,0,0,0.5)]  md:text-7xl lg:text-8xl dark:text-white">
          Product List
        </h1>

        <p className="mb-8 md:px-3 text-lg font-normal text-black lg:text-xl max-w-[980px] dark:text-gray-200">
          My solution to a task where it was required to request data of the
          product list from the API and display the list with a search input and
          so that each product would be a link to a seperate page.
        </p>

        <LinkArrowBtn text="See Product List" href="/product-list" />

        <div className="py-8 md:px-3 mx-auto max-w-screen-xl lg:py-16">
          <div className="flex flex-col items-baseline text-start bg-gray-100 dark:bg-gray-800 border border-gray-400/70 shadow-lg dark:border-gray-700 rounded-lg p-8 xl:p-10 mb-8">
            <div className="bg-blue-200 text-blue-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded-md dark:bg-gray-700 dark:text-blue-400 mb-2">
              <svg
                className="w-2.5 h-2.5 me-1.5"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
              </svg>
              About
            </div>

            <h1 className="text-gray-900 dark:text-white text-4xl xs:text-5xl  font-extrabold mb-3">
              Project overview
            </h1>

            <p className="text-lg font-normal text-gray-700 dark:text-gray-400 mb-6">
              Main task was to use Typescript and React, fetch data from the
              API, and display it. As a bonus, it was required to use NextJS and
              TailwindCSS. I implemented the debounced search with prefetched
              links and also additional filtering and sorting functionality as
              well as pagination. For my components, I made a code snippets
              section for easier browsing and copying source code fetched from
              the GitHub repository.
            </p>

            <LinkArrowBtn text="Project Repository" href="#" />
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            <div className="flex flex-col items-baseline 600px:items-center md:items-baseline text-start bg-gray-100 dark:bg-gray-800 border border-gray-400/70 shadow-lg dark:border-gray-700 rounded-lg p-8 xl:p-10">
              <div className="bg-green-200 text-green-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded-md dark:bg-gray-700 dark:text-green-400">
                <svg
                  className="w-2.5 h-2.5 me-1.5"
                  aria-hidden="true"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="currentColor"
                  viewBox="0 0 18 18"
                >
                  <path d="M17 11h-2.722L8 17.278a5.512 5.512 0 0 1-.9.722H17a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1ZM6 0H1a1 1 0 0 0-1 1v13.5a3.5 3.5 0 1 0 7 0V1a1 1 0 0 0-1-1ZM3.5 15.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2ZM16.132 4.9 12.6 1.368a1 1 0 0 0-1.414 0L9 3.55v9.9l7.132-7.132a1 1 0 0 0 0-1.418Z" />
                </svg>
                Specs
              </div>

              <h1 className="text-gray-900 dark:text-white text-4xl xs:text-5xl lg:text-4xl xl:text-5xl font-extrabold mb-4 mt-3">
                App Features
              </h1>

              <ul
                role="list"
                className="flex flex-col gap-4 justify-around h-full text-xl xs:text-2xl text-gray-700 dark:text-gray-400"
              >
                <AppFeatureItem text="Server-side Rendering" />

                <AppFeatureItem text="Prefetching Links" />

                <AppFeatureItem text="Suspense and Error Boundaries" />

                <AppFeatureItem text="Hosting app on Vercel" />

                <AppFeatureItem text="Code Snippets" />

                <AppFeatureItem text="Theme Toggling" />

                <AppFeatureItem text="Responsiveness" />
              </ul>
            </div>

            <div className="flex flex-col items-baseline text-start bg-gray-100 dark:bg-gray-800 border border-gray-400/70 shadow-lg dark:border-gray-700 rounded-lg p-8 xl:p-10">
              <div className="bg-purple-200 text-purple-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded-md dark:bg-gray-700 dark:text-purple-400 mb-2">
                <svg
                  className="w-2.5 h-2.5 me-1.5"
                  aria-hidden="true"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 20 16"
                >
                  <path
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M5 4 1 8l4 4m10-8 4 4-4 4M11 1 9 15"
                  />
                </svg>
                Stack
              </div>

              <h1 className="text-gray-900 dark:text-white text-4xl xs:text-5xl lg:text-4xl xl:text-5xl font-extrabold mb-2">
                Technologies Used
              </h1>

              <ul className="mt-4 space-y-4 w-full">
                <li>
                  <TechLink
                    name="TypeScript"
                    href="https://www.typescriptlang.org/"
                    iconHref="/assets/images/techIcons/typescriptIcon.svg"
                    iconClassName="h-6"
                    version="v-^5"
                  />
                </li>

                <li>
                  <TechLink
                    name="React"
                    href="https://react.dev/"
                    iconHref="/assets/images/techIcons/reactIcon.svg"
                    iconClassName="h-6 brightness-[0.8] dark:brightness-100"
                    version="v-^18"
                  />
                </li>

                <li>
                  <TechLink
                    name="NextJS"
                    href="https://nextjs.org/"
                    iconHref="/assets/images/techIcons/nextjsIcon.svg"
                    iconClassName="h-6"
                    version="v-14.0.1"
                  />
                </li>

                <li>
                  <TechLink
                    name="TailwindCSS"
                    href="https://tailwindcss.com/"
                    iconHref="/assets/images/techIcons/tailwindIcon.svg"
                    iconClassName="h-6"
                    version="v-^3.3.5"
                  />
                </li>

                <li>
                  <TechLink
                    name="Vercel"
                    href="https://vercel.com/"
                    iconHref="/assets/images/techIcons/vercelIcon.svg"
                    iconClassName="h-5"
                    version="v-^3.3.5"
                  />
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-gradient-to-b from-gray-400 to-transparent dark:from-blue-900 w-full h-full absolute top-0 left-0 z-0"></div>
    </section>
  );
}
